package en1.common
/**
 * Error codes for app
 * */
const val ERROR_YANDEX_REQUEST_FAILED: Int = 1012
const val ERROR_UNKNOWN_CALLBACK: Int = 1013
const val ERROR_MSG_IN_YANDEX_JSON: Int = 1014
const val ERROR_YANDEX_CAPTCHA_REQUIRED: Int = 1015
const val ERROR_YANDEX_JSON_PARSE_FAILED: Int = 1016

val ERRORS_MAP = mapOf(
    ERROR_YANDEX_REQUEST_FAILED to "Yandex request failed",
    ERROR_UNKNOWN_CALLBACK to "Unknown callback",
    ERROR_MSG_IN_YANDEX_JSON to "ERROR_MSG_IN_YANDEX_JSON",
    ERROR_YANDEX_CAPTCHA_REQUIRED to "ERROR_YANDEX_CAPTCHA_REQUIRED",
    ERROR_YANDEX_JSON_PARSE_FAILED to "Failed to parse Yandex JSON",
)